packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # Astro
  astro: ^5.16.6
  '@astrojs/check': ^0.9.5
  '@astrojs/mdx': ^4.3.13
  '@astrojs/rss': ^4.0.13
  '@astrojs/sitemap': ^3.6.0
  '@astrojs/svelte': ^7.2.4

  # Tailwind
  tailwindcss: ^4.1.18
  '@tailwindcss/forms': ^0.5.11
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': ^4.1.18

  # Svelte
  svelte: ^5.46.0
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  lucide-svelte: ^0.561.0

  # Core
  typescript: ^5.9.3
  zod: ^4.2.1
  clsx: ^2.1.1
  tailwind-merge: ^3.3.1
  sharp: ^0.34.5

  # Formatting & Linting
  '@biomejs/biome': ^2.3.10
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-astro: ^1.5.0
  prettier: ^3.6.2
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-svelte: ^3.4.1
  husky: ^9.1.7
  lint-staged: ^16.2.6

  # Maps
  leaflet: ^1.9.4
  '@types/leaflet': ^1.9.21

  # Casoon
  '@casoon/atlas-styles': ^0.0.9
  '@casoon/astro-speed-measure': 0.1.4
  '@casoon/astro-webvitals': ^0.2.1

  # Fonts
  '@fontsource/archivo': ^5.2.8
  '@fontsource/crimson-text': ^5.2.7
  '@fontsource/dm-sans': ^5.2.8
  '@fontsource/fira-code': ^5.2.7
  '@fontsource/inter': ^5.2.8
  '@fontsource/jetbrains-mono': ^5.2.8
  '@fontsource/lora': ^5.2.8
  '@fontsource/manrope': ^5.2.8
  '@fontsource/merriweather': ^5.2.11
  '@fontsource/montserrat': ^5.2.8
  '@fontsource/playfair-display': ^5.2.8
  '@fontsource/poppins': ^5.2.7
  '@fontsource/raleway': ^5.2.8
  '@fontsource/source-serif-4': ^5.2.9
  '@fontsource/space-grotesk': ^5.2.10
  '@fontsource/work-sans': ^5.2.8

  # Dev Tools
  '@types/node-fetch': ^2.6.13
  lighthouse: ^13.0.1
  npm-run-all: ^4.1.5
  wait-on: ^9.0.3
